name: CI/CD Pipeline for FastAPI - Azure Web App

on:
  push:
    branches:
      - main  # Le pipeline se déclenche à chaque push sur la branche 'main'
  pull_request:
    branches:
      - main  # Le pipeline se déclenche aussi lors des pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Utilise la version de Python que tu utilises dans ton projet

      # Installer les dépendances du projet
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assure-toi que le fichier 'requirements.txt' est à jour

      # Lancer les tests automatisés
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Lance les tests avec pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ce job dépend du succès du job 'build'

    steps:
      # Vérifier à nouveau le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurer les informations d'Azure
      - name: 'Set up Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}  # Le nom de ton Web App Azure
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Le publish profile de ton Web App
          package: '.'  # Le répertoire contenant ton application

      # Optionnel : Ajouter d'autres étapes de déploiement si nécessaire, comme les migrations de base de données
